### ISSUE TITLE
Allow different output directory other than dist

### ISSUE THREAD

**Issue by CuteWaterBeary** [ophidian-lib/build#2]
Please give an option to override the output directory cause this is the only thing making this unusable for me.

**Comment by pjeby** [comment]
Can you symlink your target directory to `dist`?

**Comment by CuteWaterBeary** [comment]
I could but that would mess things up for using the repo on different OS's where the goal is just to clone and run.

**Comment by CuteWaterBeary** [comment]
I tried to remove this to build the pane-relief without it but then I get a ophidian core error https://github.com/ophidian-lib/core/issues/4

**Comment by pjeby** [comment]
1. If the target you want is the same on all machines (e.g. for an embedded test vault), just check the symlink into git.  If the target is different, shouldn't you be using `OBSIDIAN_TEST_VAULT` to set the dev build directory?
2. ophidian/core requires ophidian/build, or a builder with compatible settings; most of my plugins use ophidian/core.

**Comment by CuteWaterBeary** [comment]
Oh okay. I didnt realize you had more plugins that depended on this and how the setup should be.
